// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lamwycpfcrfvwpbelhse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbXd5Y3BmY3JmdndwYmVsaHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDE5NzAsImV4cCI6MjA3Mjg3Nzk3MH0.q0Bprr19dSL66p0KJU5m-C1BiY8_0J1uP8MqCs70CoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});